# Generated by Django 3.0.9 on 2021-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20211031_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='api_key',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tranaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
