# Generated by Django 3.0.9 on 2021-10-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20211031_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
    ]
