# Generated by Django 3.0.9 on 2021-11-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='platform',
            field=models.CharField(choices=[('PAYPAL', 'paypal'), ('PAYSTACK', 'paystack'), ('STRIPE', 'stripe'), ('FLUTTERWAVE', 'rave_payment'), ('COINBASE', 'coinbase')], max_length=15, verbose_name='Payment Platform'),
        ),
    ]
